# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'table_coffee_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(799, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.table_coffee = QtWidgets.QTableWidget(self.centralwidget)
        self.table_coffee.setGeometry(QtCore.QRect(0, 0, 801, 601))
        self.table_coffee.setObjectName("table_coffee")
        self.table_coffee.setColumnCount(7)
        self.table_coffee.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_coffee.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_coffee.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_coffee.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_coffee.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_coffee.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_coffee.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_coffee.setHorizontalHeaderItem(6, item)
        self.table_coffee.horizontalHeader().setDefaultSectionSize(110)
        self.table_coffee.horizontalHeader().setMinimumSectionSize(65)
        self.table_coffee.horizontalHeader().setStretchLastSection(True)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        item = self.table_coffee.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.table_coffee.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Название сорта"))
        item = self.table_coffee.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Степень обжарки"))
        item = self.table_coffee.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Молотый/в зернах"))
        item = self.table_coffee.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Описание вкуса"))
        item = self.table_coffee.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Цена"))
        item = self.table_coffee.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Объем упаковки"))
